#!/usr/bin/env bash
# Configures the /etc/hosts file with custom IPs
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
